# Generated by Django 4.0.3 on 2022-03-22 09:26

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SewingPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name',
                 models.CharField(db_index=True, help_text='Unique name (maximum 60 SLUG characters)', max_length=60,
                                  unique=True, validators=[
                         django.core.validators.RegexValidator(re.compile('^[-a-zA-Z0-9_]+\\Z'),
                                                               'Enter a valid “slug” consisting of letters, numbers, underscores or hyphens.',
                                                               'invalid')], verbose_name='Name')),
                ('description',
                 models.CharField(blank=True, help_text='Description (maximum 300 characters)', max_length=300,
                                  verbose_name='Description')),
                ('drawing',
                 models.JSONField(blank=True, help_text='JSON representation of the drawing', max_length=100000,
                                  verbose_name='drawing')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
