# Generated by Django 4.0.3 on 2022-03-22 13:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('sewpatd', '0003_alter_sewingpattern_drawing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sewingpattern',
            name='name',
            field=models.CharField(db_index=True, help_text='Unique name (maximum 60 characters)', max_length=60,
                                   unique=True, verbose_name='Name'),
        ),
    ]
