# Generated by Django 4.0.3 on 2022-03-30 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('sewpatd', '0004_alter_sewingpattern_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sewingpattern',
            name='description',
            field=models.CharField(blank=True, help_text='Description (maximum Ĭharacters)', max_length=300,
                                   verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='sewingpattern',
            name='name',
            field=models.CharField(db_index=True, help_text='Unique name (maximum <haracters)', max_length=60,
                                   unique=True, verbose_name='Name'),
        ),
        migrations.CreateModel(
            name='Drawing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Unique name (maximum <haracters)', max_length=60,
                                          unique=True, verbose_name='Name')),
                ('description',
                 models.CharField(blank=True, help_text='Description (maximum Ĭharacters)', max_length=300,
                                  verbose_name='Description')),
                ('sewing_pattern',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drawings',
                                   to='sewpatd.sewingpattern', verbose_name='Link to pattern')),
            ],
        ),
    ]
