# Generated by Django 4.0.3 on 2022-03-30 09:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('sewpatd', '0005_alter_sewingpattern_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='drawing',
            name='drawing',
            field=models.JSONField(blank=True, help_text='JSON representation of the drawing', max_length=100000,
                                   null=True, verbose_name='drawing'),
        ),
    ]
