# Generated by Django 4.0.3 on 2022-03-30 11:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('sewpatd', '0012_alter_sewingpattern_drawing'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drawing',
            old_name='drawing',
            new_name='image',
        ),
    ]
