# Generated by Django 4.0.3 on 2022-03-30 12:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('sewpatd', '0013_rename_drawing_drawing_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sewingpattern',
            name='drawing',
        ),
        migrations.AlterField(
            model_name='drawing',
            name='image',
            field=models.JSONField(blank=True, help_text='Image in custom JSON format (maximum 100000 bytes)',
                                   max_length=100000, null=True, verbose_name='Image'),
        ),
    ]
