# Generated by Django 4.0.3 on 2022-03-30 12:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('sewpatd', '0014_remove_sewingpattern_drawing_alter_drawing_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='drawing',
            options={'ordering': ['name']},
        ),
        migrations.AddConstraint(
            model_name='drawing',
            constraint=models.UniqueConstraint(fields=('sewing_pattern', 'name'),
                                               name='Unique name per sewing pattern'),
        ),
    ]
