# Generated by Django 4.0.3 on 2022-03-30 14:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('sewpatd', '0017_drawing_curves_drawing_points_drawing_segments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drawing',
            name='image',
        ),
    ]
